### PR TITLE
Added automatic jsonnet execution at save time.

### PR DESCRIPTION
**Pull request by ahakanbaba**
Added documentation, a vim command, a user callable function and an
autocommand that gets executed at every save.

The defaults are hight configurable with options that are also
documented in this change.

### CODE REVIEW

**Comment by ahakanbaba** [comment]
@sparkprime 
Hi Dave, 
please take a look at this squashed pull request. 
Thanks

**Comment by ahakanbaba** [comment]
Hi, 
May I ask for some of your attention for this pull request. 
It would be great to merge this to master if you do not have any other issues with it ? 
Thanks

**Comment by sparkprime** [comment]
Thanks for your contribution!

**Comment by ahakanbaba** [comment]
No problem. I am looking forward to benefit from this change I hope other
people also use it and we get some feedback.
I will definitely promote this repo inside Box and encourage people to use
it.
Thanks for your comments and help along the way.
Hakan

**Pull request merged**
