### PR TITLE
syntax: Update syntax elements for jsonnet v0.19.1

### PR DESCRIPTION
**Pull request by camh-**
Update the standard library names and add the `importbin` statement to
update the syntax highlighting to jsonnet v0.19.1.

The standard library names have been automatically generated with the
following command:

    PROG='std.lines(["syn match Constant \"std.%s\"" % fn for fn in std.objectFieldsAll(std) if fn[0] >= "a" && fn[0] <= "z"])''
    go run github.com/google/go-jsonnet/cmd/jsonnet@v0.19.1 --string - <<<"${PROG}"

This should make it easier to keep up-to-date with additions to the
standard library, as it was missing some rather old additions. Seems to
have been rather adhoc.

As part of this automation, the builtins and `std.jsonnet` have been
combined as there is no way to determine which names are builtin and
which come from `std.jsonnet`. Manually maintaining the distinction is
pointless busywork, and that fell behind anyway as a bunch of
`std.jsonnet` functions have been migrated to builtins for performance
reasons.

The automation script lists the names in the `std` object, ignoring all
names that do not start with a lower-case letter. This removes some
internal names that should not be added to the syntax highlighting.

The `importbin` statement was manually added.

### CODE REVIEW

**Comment by sparkprime** [comment]
Thanks for the PR.  Do you think there's anything from https://github.com/google/vim-jsonnet/pull/24 that should be brought in?  The regexes at the end specifically

**Comment by camh-** [comment]
@sparkprime I don't know enough about vim syntax highlighting to know what the rest of that PR is doing. :shrug:

**Comment by sparkprime** [comment]
Nor me.  Thanks for taking a look :)

**Comment by camh-** [comment]
I'll try to remember to take another look later. The individual commits by @mattwilder seem to be cohesive enough to understand with good commit messages that I may be able to make some sense of vimscript / syntax hightlight.

**Pull request merged**
